### ISSUE TITLE
net.md_5.bungee.api.ServerPing not working

### ISSUE THREAD

**Issue by tsao-chi1** [mikroskeemsrealm/Firefly#12]
All queue plugins using `net.md_5.bungee.api.ServerPing` to check if a server is online don't work.
Version: https://bucket.mikroskeem.eu/mikrocord/Firefly_2020-05-09_22-54-41.jar
Example queue plugin: ajQueue
message sent to client: `The server you are queued for is restarting. You are in position 1 of 1.`
config:
```
server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts: {}
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - firefly.command.restart
log_pings: false
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: bungeecord
groups: {}
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another SSBungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
    ip_forward: bungeecord
  st:
    motd: '&1Just another SSBungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
    ip_forward: bungeecord
```
```
shutdown:
  wait_for_all_players_to_disconnect_infinitely: true
log:
  ignored_commands:
  - login
  - register
  - changepassword
  invalid_query_packets: false
  noisy_packet_decode_exception: false
  invalid_login_process_packets: false
allow_proxying_proxies: false
packets:
  drop_invalid_packet_senders: true
  log_packet_decode_errors: false
  handle_legacy_ping: true
prometheus:
  enabled: false
  listen_host: 127.0.0.1
  listen_port: 8888
query:
  populate_plugins: false
performance:
  allow_tablist_rewrite: true
  intern_scoreboard_team_strings: false
velocity_modern_forwarding:
  secret: a6uOw5EXJJw4
networking:
  tcp_fast_open:
    enabled: true
    mode: 1
restart:
  message: Proxy is restarting
  script_path: ./restart.sh
```

**Comment by tsao-chi1** [comment]
decompiled code:
```
            this.getProxy().getServers().get(server).ping((Callback)new Callback<ServerPing>() {
                public void done(final ServerPing result, final Throwable error) {
                    Main.this.servers.put(server, error == null);
                }
            });
```

**Comment by mikroskeem** [comment]
ajQueue can be downloaded from https://www.spigotmc.org/resources/ajqueue.78266/ right?

**Comment by mikroskeem** [comment]
Assuming yes.

BungeeCord introduced [remote ping caching](https://github.com/SpigotMC/BungeeCord/commit/636c02077259ca8addec2d3ce221a18981a46296) some time ago, maybe that is interfering?

**Comment by tsao-chi1** [comment]
> ajQueue can be downloaded from https://www.spigotmc.org/resources/ajqueue.78266/ right?
right

**Comment by tsao-chi1** [comment]
config:
```
server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts: {}
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - firefly.command.restart
log_pings: false
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: bungeecord
groups: {}
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 6420a0f5-6610-49c9-aec6-fc348c0131ae
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another SSBungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
    ip_forward: bungeecord
  st:
    motd: '&1Just another SSBungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
    ip_forward: bungeecord
```
```
shutdown:
  wait_for_all_players_to_disconnect_infinitely: true
log:
  ignored_commands:
  - login
  - register
  - changepassword
  invalid_query_packets: false
  noisy_packet_decode_exception: false
  invalid_login_process_packets: false
allow_proxying_proxies: false
packets:
  drop_invalid_packet_senders: true
  log_packet_decode_errors: false
  handle_legacy_ping: true
prometheus:
  enabled: false
  listen_host: 127.0.0.1
  listen_port: 8888
query:
  populate_plugins: false
performance:
  allow_tablist_rewrite: true
  intern_scoreboard_team_strings: false
velocity_modern_forwarding:
  secret: a6uOw5EXJJw4
networking:
  tcp_fast_open:
    enabled: true
    mode: 1
restart:
  message: Proxy is restarting
  script_path: ./restart.sh
```
